baseURL = "https://lhan.quest"
title = "Lin Han's Blog"
theme = "paper"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

[params]
    # show header social icons
    # twitter = 'YOUR_TWITTER_ID'     # twitter.com/YOUR_TWITTER_ID
    github = 'HenryHK'       # github.com/YOUR_GITHUB_ID
    # instagram = 'YOUR_INSTAGRAM_ID' # instagram.com/YOUR_INSTAGRAM_ID
    # rss = true                      # show rss icon with link

    # show home page profile
    avatar = 'henryhan.hku@gmail.com'       # Gravatar email or image url(e.g. "https://deno.land/logo.svg")
    name = 'Lin Han'
    bio = 'A gopher, (n)vimmer, and surely a software engineer'

    # misc
    disableHLJS = true              # disable requesting highlight.js
    monoDarkIcon = true             # show monochrome dark mode icon

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
